# Generated by Django 3.0.5 on 2021-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('javascript', models.CharField(default='', max_length=1000)),
                ('css_styles', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
