module.exports = {
  projects: [
    '<rootDir>/apps/marketing-app',
    '<rootDir>/libs/client/marketing-app',
    '<rootDir>/libs/marketing-app/marketing-app',
    '<rootDir>/libs/marketing-app/landing-page',
    '<rootDir>/apps/market-app',
    '<rootDir>/libs/market-app/sign-ups',
    '<rootDir>/libs/market-app/sign-in',
    '<rootDir>/libs/market-app/landing-page',
    '<rootDir>/libs/market-app/top-menu',
    '<rootDir>/libs/market-app/main-filter',
    '<rootDir>/libs/market-app/item-list',
    '<rootDir>/libs/market-app/footer',
    '<rootDir>/libs/market-app/top-banner',
    '<rootDir>/libs/market-app/top-bar-settings',
    '<rootDir>/libs/market-app/item-details',
    '<rootDir>/libs/shared/account-syn-api',
    '<rootDir>/libs/shared/auth-guard',
  ],
};
