# Generated by Django 3.0.5 on 2021-05-28 15:12

import customFields.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('field_id', models.UUIDField(default=uuid.UUID('28038e91-20ca-41c6-800f-2dc2caa315ed'), editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('LOCATION', 'Location'), ('DATE', 'Date'), ('FILE', 'File')], max_length=200)),
                ('associated_model', models.CharField(choices=[('USER', 'User'), ('LISTING', 'Listing')], max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldItem',
            fields=[
                ('field_content_id', models.UUIDField(default=uuid.UUID('2ba4de26-297d-490c-8a20-a90e0a91e158'), primary_key=True, serialize=False)),
                ('field_content', models.CharField(max_length=200)),
                ('field_upload', models.FileField(default='', upload_to=customFields.models.field_directory_path)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customFields.CustomField')),
            ],
        ),
    ]
