# Generated by Django 3.0.5 on 2021-06-19 10:09

import customFields.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('LOCATION', 'Location'), ('DATE', 'Date'), ('FILE', 'File')], max_length=200)),
                ('options', models.CharField(default='', max_length=1000)),
                ('object_id', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True, help_text='Is this field visible to the public?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_content', models.CharField(max_length=500)),
                ('field_upload', models.FileField(blank=True, upload_to=customFields.models.field_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customFields.CustomField')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
