# Generated by Django 3.0.5 on 2021-06-19 17:25

import customFields.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('LOCATION', 'Location'), ('DATE', 'Date'), ('FILE', 'File')], max_length=200)),
                ('options', models.CharField(default='', max_length=1000)),
                ('is_required', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True, help_text='Is this field visible to the public?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing_field', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Listing')),
                ('user_field', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('file_upload', models.FileField(blank=True, upload_to=customFields.models.field_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customFields.CustomField')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
