# Generated by Django 3.0.5 on 2021-06-12 17:31

import customFields.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('LOCATION', 'Location'), ('DATE', 'Date'), ('FILE', 'File')], max_length=200)),
                ('associated_model', models.CharField(choices=[('USER', 'User'), ('LISTING', 'Listing')], max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_content', models.CharField(max_length=200)),
                ('field_upload', models.FileField(default='', upload_to=customFields.models.field_directory_path)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customFields.CustomField')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
