# Generated by Django 3.0.5 on 2021-05-27 10:29

import customfields.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('field_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('DROPDOWN', 'Dropdown'), ('TEXT', 'Text'), ('NUMBER', 'Number'), ('LOCATION', 'Location'), ('DATE', 'Date'), ('FILE', 'File')], max_length=200)),
                ('associated_model', models.CharField(choices=[('USER', 'User'), ('LISTING', 'Listing')], max_length=200)),
                ('field_content', models.CharField(max_length=200)),
                ('field_upload', models.FileField(default='', upload_to=customfields.models.field_directory_path)),
                ('is_required', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
    ]
