# Generated by Django 3.0.5 on 2021-05-28 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('39af7484-04a8-4dc5-b1f4-0f3fa38b6562'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('66ec7a17-7326-4a63-b233-846c2b316a6c'), primary_key=True, serialize=False),
        ),
    ]
