# Generated by Django 3.0.5 on 2021-06-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0002_auto_20210528_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('6da0a5ff-9bab-4150-89c6-d1d3eb3384ba'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('b16f294a-8a4c-4016-b9b1-575e82af587a'), primary_key=True, serialize=False),
        ),
    ]
