# Generated by Django 3.0.5 on 2021-06-09 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0003_auto_20210609_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('d7d6812f-49af-4ee7-942b-e5f8ca136f33'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('a4d75158-0550-474f-8ae8-0822173e9c9e'), primary_key=True, serialize=False),
        ),
    ]
