# Generated by Django 3.0.5 on 2021-06-10 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0004_auto_20210609_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('82dbd025-6067-41a7-8a65-f26a0193f55c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('dcc4bfb2-5d50-4106-bd60-4f180df27356'), primary_key=True, serialize=False),
        ),
    ]
