# Generated by Django 3.0.5 on 2021-06-10 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0006_auto_20210610_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('62c94165-616e-4b44-9679-7206a1b99d64'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('1f7ed1bf-f042-444c-b294-dde434290696'), primary_key=True, serialize=False),
        ),
    ]
