# Generated by Django 3.0.5 on 2021-06-10 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0007_auto_20210610_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('e28f911f-69c6-498f-aba5-90b7ace39b8e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('fba43a7f-38dc-459c-895a-e016fa038f05'), primary_key=True, serialize=False),
        ),
    ]
