# Generated by Django 3.0.5 on 2021-06-10 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0009_auto_20210610_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('d3810309-47dc-4584-9c72-2307ca073802'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('d626485f-5362-416f-924c-bc2bbd158ced'), primary_key=True, serialize=False),
        ),
    ]
