# Generated by Django 3.0.5 on 2021-06-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0010_auto_20210610_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('0acfbd44-02e8-4ad1-9980-bd002e267b20'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('c25831f5-b75a-47cd-a578-ee13565dc7c2'), primary_key=True, serialize=False),
        ),
    ]
