# Generated by Django 3.0.5 on 2021-06-11 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0011_auto_20210611_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('241abbc2-cf9d-4c99-9516-60b127856eaa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('64b3e01d-4903-4583-8854-2e461ed3eaea'), primary_key=True, serialize=False),
        ),
    ]
