# Generated by Django 3.0.5 on 2021-06-11 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0012_auto_20210611_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('630d6a3e-3be1-4dab-ac6d-ef299849d340'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('283593d6-921e-4a31-b8ac-26b9954850b6'), primary_key=True, serialize=False),
        ),
    ]
