# Generated by Django 3.0.5 on 2021-06-11 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0013_auto_20210611_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('700abec1-4eb7-4945-af80-decc4820d49e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('8903edde-ec74-4eed-a651-d2b4ab4bfbda'), primary_key=True, serialize=False),
        ),
    ]
