# Generated by Django 3.0.5 on 2021-06-12 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customFields', '0014_auto_20210611_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_id',
            field=models.UUIDField(default=uuid.UUID('0d582cf1-4951-4d66-b11b-564f3f19482d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customfielditem',
            name='field_content_id',
            field=models.UUIDField(default=uuid.UUID('2e7c5bf9-75f1-478e-854a-53e8f91b5ae7'), primary_key=True, serialize=False),
        ),
    ]
