# Generated by Django 3.0.5 on 2021-05-28 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('b502265e-1292-43f4-aa36-92bf4b905a97'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='handler_name',
            field=models.CharField(help_text='Name of the payment gateway', max_length=200),
        ),
    ]
