# Generated by Django 3.0.5 on 2021-05-28 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0002_auto_20210528_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('6fee8d1e-6feb-47d8-8657-3328a890145d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
