# Generated by Django 3.0.5 on 2021-06-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0003_auto_20210528_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('b1ce5ad2-6331-48df-990d-3ae28f002998'), editable=False, primary_key=True, serialize=False),
        ),
    ]
