# Generated by Django 3.0.5 on 2021-06-09 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0004_auto_20210609_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('2f6724c2-4b36-4f21-8b30-75f87c300596'), editable=False, primary_key=True, serialize=False),
        ),
    ]
