# Generated by Django 3.0.5 on 2021-06-10 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0005_auto_20210609_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('2aacf270-f8b8-48f4-a574-e943d0ef4e05'), editable=False, primary_key=True, serialize=False),
        ),
    ]
