# Generated by Django 3.0.5 on 2021-06-10 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0006_auto_20210610_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('73bd7166-7a5b-4c82-9596-5f43cd7de15e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
