# Generated by Django 3.0.5 on 2021-06-10 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0007_auto_20210610_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('55e17d5e-ec6c-4d25-82a1-43f1a5bb8b1e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
