# Generated by Django 3.0.5 on 2021-06-10 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0008_auto_20210610_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('a4122e75-58d5-4b4b-aba4-e9821bb5456a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
