# Generated by Django 3.0.5 on 2021-06-10 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0009_auto_20210610_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('9f6e5ddc-5ec2-4938-83b7-da634b79bdac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
