# Generated by Django 3.0.5 on 2021-06-10 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0010_auto_20210610_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('fc22d13c-032f-47e2-ac38-6d7b94712324'), editable=False, primary_key=True, serialize=False),
        ),
    ]
