# Generated by Django 3.0.5 on 2021-06-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0011_auto_20210610_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('05654e85-9fcc-41a7-9fbd-088c2ced18f5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
