# Generated by Django 3.0.5 on 2021-06-11 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0012_auto_20210611_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('8496c533-d6ef-46c2-b1a9-24933fda1b22'), editable=False, primary_key=True, serialize=False),
        ),
    ]
