# Generated by Django 3.0.5 on 2021-06-11 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0013_auto_20210611_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('844bb14c-79be-428d-8ff4-2da8a5591e0c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
