# Generated by Django 3.0.5 on 2021-06-11 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0014_auto_20210611_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('dcb2944d-7b42-4feb-a00b-aab0fefcabf0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
