# Generated by Django 3.0.5 on 2021-06-12 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0015_auto_20210611_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_id',
            field=models.UUIDField(default=uuid.UUID('69fe8e40-e2b0-432c-9086-dffb20eef3a3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
