# Generated by Django 3.0.5 on 2021-05-28 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.UUIDField(default=uuid.UUID('690ed580-9a9a-4658-b665-71f4229445b7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
