# Generated by Django 3.0.5 on 2021-05-28 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210528_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.UUIDField(default=uuid.UUID('f2ff6aeb-5ad0-4fcc-a9ca-1ca6cab93bef'), editable=False, primary_key=True, serialize=False),
        ),
    ]
