from django.db import models

# Create your models here.


class Settings(models.Model):
    """
    Transaction FLow, related to marketplace plans
    """

    print("hello")


# "id",
# "uuid",
# "ident",
# "domain",
# "use_domain",
# "created_at",
# "updated_at",
# "settings",
# "consent",
# "transaction_agreement_in_use",
# "email_admins_about_new_members",
# "use_fb_like",
# "real_name_required",
# "automatic_newsletters",
# "join_with_invite_only",
# "allowed_emails",
# "users_can_invite_new_users",
# "private", "label",
# "show_date_in_listings_list",
# "all_users_can_add_news",
# "custom_frontpage_sidebar",
# "event_feed_enabled",
# "slogan",
# "description",
# "country",
# "members_count",
# "user_limit",
# "monthly_price_in_euros",
# "logo_file_name",
# "logo_content_type",
# "logo_file_size",
# "logo_updated_at",
# "cover_photo_file_name",
# "cover_photo_content_type",
# "cover_photo_file_size",
# "cover_photo_updated_at",
# "small_cover_photo_file_name",
# "small_cover_photo_content_type",
# "small_cover_photo_file_size",
# "small_cover_photo_updated_at",
# "custom_color1",
# "custom_color2",
# "slogan_color",
# "description_color",
# "stylesheet_url",
# "stylesheet_needs_recompile",
# "service_logo_style",
# "currency",
# "facebook_connect_enabled",
# "minimum_price_cents",
# "hide_expiration_date",
# "facebook_connect_id",
# "facebook_connect_secret",
# "google_analytics_key",
# "google_maps_key",
# "name_display_type",
# "twitter_handle",
# "use_community_location_as_default",
# "preproduction_stylesheet_url",
# "show_category_in_listing_list",
# "default_browse_view",
# "wide_logo_file_name",
# "wide_logo_content_type",
# "wide_logo_file_size",
# "wide_logo_updated_at",
# "listing_comments_in_use",
# "show_listing_publishing_date",
# "require_verification_to_post_listings",
# "show_price_filter",
# "price_filter_min",
# "price_filter_max",
# "automatic_confirmation_after_days",
# "favicon_file_name",
# "favicon_content_type",
# "favicon_file_size",
# "favicon_updated_at",
# "default_min_days_between_community_updates",
# "listing_location_required",
# "custom_head_script",
# "follow_in_use",
# "logo_processing",
# "wide_logo_processing",
# "cover_photo_processing",
# "small_cover_photo_processing",
# "favicon_processing",
# "deleted",
# "end_user_analytics",
# "show_slogan",
# "show_description",
# "hsts_max_age",
# "footer_theme",
# "footer_copyright",
# "footer_enabled",
# "logo_link",
# "google_connect_enabled",
# "google_connect_id",
# "google_connect_secret",
# "linkedin_connect_enabled",
# "linkedin_connect_id",
# "linkedin_connect_secret",
# "pre_approved_listings",
# "allow_free_conversations",
# "email_admins_about_new_transactions",
# "show_location",
# "fuzzy_location",
# "recaptcha_site_key",
# "recaptcha_secret_key"
