# Generated by Django 3.0.5 on 2021-06-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallivaUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
