# Generated by Django 3.0.5 on 2021-06-09 20:31

from django.db import migrations, models
import mallivaUsers.models


class Migration(migrations.Migration):

    dependencies = [
        ('mallivaUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=mallivaUsers.models.user_directory_path),
        ),
    ]
