# Generated by Django 3.0.5 on 2021-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallivaUsers', '0002_auto_20210609_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_of_service_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
