# Generated by Django 3.0.5 on 2021-05-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallivaUsers', '0003_auto_20210517_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=200),
        ),
    ]
