# Generated by Django 3.0.5 on 2021-05-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mallivaUsers', '0004_auto_20210518_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='marketplace_id',
            new_name='marketplace',
        ),
    ]
