# Generated by Django 3.0.5 on 2021-05-28 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('a6667a53-5586-461c-bf19-27683b7adad6'), primary_key=True, serialize=False),
        ),
    ]
