# Generated by Django 3.0.5 on 2021-05-28 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210528_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('b9cfb139-8931-4b5c-b154-658c64e335c3'), primary_key=True, serialize=False),
        ),
    ]
