# Generated by Django 3.0.5 on 2021-06-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210528_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('2104e175-9df0-4282-ae11-d46ade9bb055'), primary_key=True, serialize=False),
        ),
    ]
