# Generated by Django 3.0.5 on 2021-06-09 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210609_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('c822319c-b732-43b0-8733-6ef4fdf957b3'), primary_key=True, serialize=False),
        ),
    ]
