# Generated by Django 3.0.5 on 2021-06-10 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210609_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('0dca1c33-b343-4e15-a48c-dcced75a5362'), primary_key=True, serialize=False),
        ),
    ]
