# Generated by Django 3.0.5 on 2021-06-10 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210610_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('72a3196e-5c77-401a-ab91-55b38e3cf19b'), primary_key=True, serialize=False),
        ),
    ]
