# Generated by Django 3.0.5 on 2021-06-10 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210610_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('c2683021-4aff-4433-871b-fe559594e2d2'), primary_key=True, serialize=False),
        ),
    ]
