# Generated by Django 3.0.5 on 2021-06-10 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20210610_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('f4ad05a4-0c4b-4156-b591-10b1894336ed'), primary_key=True, serialize=False),
        ),
    ]
