# Generated by Django 3.0.5 on 2021-06-10 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20210610_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('05b4672f-d663-4eef-8202-ea2fa286bcaa'), primary_key=True, serialize=False),
        ),
    ]
