# Generated by Django 3.0.5 on 2021-06-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20210610_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('e1ff5c9f-921e-4743-aac1-ee49ab83214b'), primary_key=True, serialize=False),
        ),
    ]
