# Generated by Django 3.0.5 on 2021-06-11 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20210611_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('75a6a264-1098-4ef8-bddd-c922880e914b'), primary_key=True, serialize=False),
        ),
    ]
