# Generated by Django 3.0.5 on 2021-06-11 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20210611_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('754e8bb2-b44b-40b5-85c7-56a7d9426cf2'), primary_key=True, serialize=False),
        ),
    ]
