# Generated by Django 3.0.5 on 2021-05-28 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('8ac7018e-2765-4eab-bebb-bf5e0e60f149'), editable=False, primary_key=True, serialize=False),
        ),
    ]
