# Generated by Django 3.0.5 on 2021-05-28 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210528_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('2e5cd8f4-f687-4a2f-8c22-4cc8f4339bd3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
