# Generated by Django 3.0.5 on 2021-06-18 18:13

from django.db import migrations, models
import django.db.models.deletion
import settingsManager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentGateways', '0001_initial'),
        ('customCodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('facebook_page', models.URLField()),
                ('twitter_page', models.URLField()),
                ('instagram_page', models.URLField()),
                ('github_page', models.URLField()),
                ('linkedin_page', models.URLField()),
                ('tiktok_page', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateStyling',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('favicon', models.ImageField(blank=True, upload_to=settingsManager.models.image_directory_path)),
                ('logo', models.ImageField(blank=True, upload_to=settingsManager.models.image_directory_path)),
                ('wide_logo', models.ImageField(blank=True, upload_to=settingsManager.models.image_directory_path)),
                ('cover_photo', models.ImageField(blank=True, upload_to=settingsManager.models.image_directory_path)),
                ('small_cover_photo', models.ImageField(blank=True, help_text='cover photo for mobile', upload_to=settingsManager.models.image_directory_path)),
                ('theme_color', models.CharField(max_length=200)),
                ('landing_page_settings', models.CharField(max_length=200)),
                ('footer_background', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('custom_codes', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customCodes.CustomCode')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slogan', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('malliva_terms_consent', models.BooleanField(default=False, help_text="track clients agreement of Malliva's latest terms of service")),
                ('transaction_agreement_in_use', models.BooleanField(default=False)),
                ('notify_admins_about_new_members', models.BooleanField(default=False)),
                ('notify_admins_about_new_transactions', models.BooleanField(default=False)),
                ('require_verification_to_post_listings', models.BooleanField(default=False)),
                ('private_marketplace', models.BooleanField(default=True)),
                ('automatic_newsletters', models.BooleanField(default=False)),
                ('invite_only_marketplace', models.BooleanField(default=False)),
                ('send_emails_from', models.EmailField(max_length=200)),
                ('preapprove_listing', models.BooleanField(default=False, help_text='listings are public by default in the marketplace')),
                ('show_date_in_listing_view', models.BooleanField(default=False)),
                ('transaction_flow', models.CharField(max_length=200)),
                ('show_location', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('default_payment_processor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='paymentGateways.PaymentGateway')),
                ('templatestyle', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='settingsManager.TemplateStyling')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
