# Generated by Django 3.0.5 on 2021-06-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateways', '0001_initial'),
        ('settingsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='default_payment_processor',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='paymentGateways.PaymentGateway'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='templatestyle',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='settingsManager.TemplateStyling'),
        ),
    ]
