# Generated by Django 3.0.5 on 2021-06-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0002_auto_20210618_1725'),
        ('settingsManager', '0002_auto_20210528_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Configuration',
        ),
    ]
