# Generated by Django 3.0.5 on 2021-05-24 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAccount',
            fields=[
                ('marketplace_id', models.UUIDField(default='30d8f27ddf3a4088a1b1c8cfef5f908b', primary_key=True, serialize=False)),
                ('marketplace_name', models.CharField(max_length=200)),
                ('marketplace_plan_id', models.CharField(default='trial', max_length=200)),
                ('database_name', models.CharField(max_length=200, unique=True)),
                ('subdomain', models.CharField(max_length=200, unique=True)),
                ('domain', models.CharField(default='', max_length=200, unique=True)),
                ('usedomain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
