# Generated by Django 3.0.5 on 2021-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='6d65804369fa48719898f2159e5e8dd7', primary_key=True, serialize=False),
        ),
    ]
