# Generated by Django 3.0.5 on 2021-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='2e3e962e4e294e8893c7653ef8cb017e', primary_key=True, serialize=False),
        ),
    ]
