# Generated by Django 3.0.5 on 2021-06-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsManager', '0003_auto_20210618_1725'),
        ('marketplaceAccounts', '0002_auto_20210618_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceaccount',
            name='marketplace_plan',
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='configuration',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='settingsManager.Configuration'),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='subscription',
            field=models.ForeignKey(default='trial', on_delete=django.db.models.deletion.SET_DEFAULT, to='marketplaceAccounts.Subscription'),
        ),
    ]
