# Generated by Django 3.0.5 on 2021-05-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0002_auto_20210527_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='5d05230e321641958121d1d005d05696', primary_key=True, serialize=False),
        ),
    ]
