# Generated by Django 3.0.5 on 2021-06-18 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplaceAccounts', '0003_auto_20210618_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='subscription',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='marketplaceAccounts.Subscription'),
        ),
    ]
