# Generated by Django 3.0.5 on 2021-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0003_auto_20210528_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='451aaca028ff468d9d7b6b36872fd501', primary_key=True, serialize=False),
        ),
    ]
