# Generated by Django 3.0.5 on 2021-05-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0003_auto_20210518_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='b8373c5df4354f5f801d60f0ef169e2e', primary_key=True, serialize=False),
        ),
    ]
