# Generated by Django 3.0.5 on 2021-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0004_auto_20210528_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='c8ffd292a50a4c199ea02a66239e8176', primary_key=True, serialize=False),
        ),
    ]
