# Generated by Django 3.0.5 on 2021-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0004_auto_20210519_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='8de122109b734593a81f95f1ad3d763a', primary_key=True, serialize=False),
        ),
    ]
