# Generated by Django 3.0.5 on 2021-06-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0005_auto_20210609_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='b6325c20aa0b4bb1b50bde8e51c7136c', primary_key=True, serialize=False),
        ),
    ]
