# Generated by Django 3.0.5 on 2021-06-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0006_auto_20210609_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='59d26c8111594ca18891c32ab3c72d72', primary_key=True, serialize=False),
        ),
    ]
