# Generated by Django 3.0.5 on 2021-06-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0007_auto_20210610_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='6baac9d6ec4b4a04aa8e660f1acf2c32', primary_key=True, serialize=False),
        ),
    ]
