# Generated by Django 3.0.5 on 2021-06-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0008_auto_20210610_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='7be8f4ced66a4846b5f6bd681db2f638', primary_key=True, serialize=False),
        ),
    ]
