# Generated by Django 3.0.5 on 2021-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0009_auto_20210610_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='6ae2082636d0482ca8ed4c52010f54c4', primary_key=True, serialize=False),
        ),
    ]
