# Generated by Django 3.0.5 on 2021-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0011_auto_20210610_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='0422b62e620140d38a7cb4473d17b506', primary_key=True, serialize=False),
        ),
    ]
