# Generated by Django 3.0.5 on 2021-06-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0012_auto_20210610_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='8df164a47d7845f6915c89928d20395c', primary_key=True, serialize=False),
        ),
    ]
