# Generated by Django 3.0.5 on 2021-06-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0013_auto_20210611_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='407279ae3fa749978b4aefb09fe3ccbf', primary_key=True, serialize=False),
        ),
    ]
