# Generated by Django 3.0.5 on 2021-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0014_auto_20210611_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='50c7c015ed974170aac964fdadbe8955', primary_key=True, serialize=False),
        ),
    ]
