# Generated by Django 3.0.5 on 2021-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceAccounts', '0015_auto_20210611_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceaccount',
            name='marketplace_id',
            field=models.UUIDField(default='ea76415e28c845c4a12d7fcdffdb17ad', primary_key=True, serialize=False),
        ),
    ]
