# Generated by Django 3.0.5 on 2021-05-28 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('cfe26e80-42f5-4975-a7f2-e0741a99baa4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
