# Generated by Django 3.0.5 on 2021-06-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210528_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('69acb0d1-eeb1-4cfd-987c-23449e772308'), editable=False, primary_key=True, serialize=False),
        ),
    ]
