# Generated by Django 3.0.5 on 2021-06-10 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210609_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('2bb0d5df-32f5-4d5b-8954-780af9ac99bb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
