# Generated by Django 3.0.5 on 2021-06-10 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210610_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('2f1580f0-db7d-41a7-a667-fdac6ff64ae4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
