# Generated by Django 3.0.5 on 2021-06-10 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210610_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('94da3364-a52a-4eb2-91b3-a6308122729c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
