# Generated by Django 3.0.5 on 2021-06-10 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210610_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('1ba1a20a-48b1-485f-b29d-aa5f066f6282'), editable=False, primary_key=True, serialize=False),
        ),
    ]
