# Generated by Django 3.0.5 on 2021-06-10 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210610_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('486cda37-f2f1-4fe5-97eb-4d94cc1c8634'), editable=False, primary_key=True, serialize=False),
        ),
    ]
