# Generated by Django 3.0.5 on 2021-06-10 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210610_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('dbaf55cc-03f0-4a5e-b6bb-1f70a4337067'), editable=False, primary_key=True, serialize=False),
        ),
    ]
