# Generated by Django 3.0.5 on 2021-06-11 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210610_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('35a78014-0fa6-4900-ae98-8acc66beb112'), editable=False, primary_key=True, serialize=False),
        ),
    ]
