# Generated by Django 3.0.5 on 2021-06-11 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210611_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('84ed18bd-4aeb-45b0-abf8-ba71b850c40a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
